/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { RequestArgs, BaseAPI } from '../base';
/**
 * AliveApi - axios parameter creator
 * @export
 */
export declare const AliveApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAliveGet: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * AliveApi - functional programming interface
 * @export
 */
export declare const AliveApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAliveGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>>;
};
/**
 * AliveApi - factory interface
 * @export
 */
export declare const AliveApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiAliveGet(options?: any): AxiosPromise<string>;
};
/**
 * AliveApi - interface
 * @export
 * @interface AliveApi
 */
export interface AliveApiInterface {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AliveApiInterface
     */
    apiAliveGet(options?: AxiosRequestConfig): AxiosPromise<string>;
}
/**
 * AliveApi - object-oriented interface
 * @export
 * @class AliveApi
 * @extends {BaseAPI}
 */
export declare class AliveApi extends BaseAPI implements AliveApiInterface {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AliveApi
     */
    apiAliveGet(options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<string, any>>;
}
