/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { RequestArgs, BaseAPI } from '../base';
import { PromotionAdministrationCommandsCreateDiscountCommandResult } from '../models';
import { PromotionAdministrationQueriesListDiscountsQueryResult } from '../models';
/**
 * PromotionAdministrationApi - axios parameter creator
 * @export
 */
export declare const PromotionAdministrationApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary İndirimin aktiflik durumunu değiştirmeyi sağlar
     * @param {number} [discountId]
     * @param {boolean} [newState]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeDiscountActiveState: (discountId?: number, newState?: boolean, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Yeni indirim kodu oluşturmayı sağlar
     * @param {string} [discountCode]
     * @param {number} [discountPercentage]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createDiscount: (discountCode?: string, discountPercentage?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary İndirim kodunu silmeye yarar
     * @param {number} [discountId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteDiscount: (discountId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary İndirim kodlarının listesini getirir
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Discount listesinde arama yapılacak kelimeyi barındırır
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listDiscounts: (page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * PromotionAdministrationApi - functional programming interface
 * @export
 */
export declare const PromotionAdministrationApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary İndirimin aktiflik durumunu değiştirmeyi sağlar
     * @param {number} [discountId]
     * @param {boolean} [newState]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeDiscountActiveState(discountId?: number, newState?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Yeni indirim kodu oluşturmayı sağlar
     * @param {string} [discountCode]
     * @param {number} [discountPercentage]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createDiscount(discountCode?: string, discountPercentage?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PromotionAdministrationCommandsCreateDiscountCommandResult>>;
    /**
     *
     * @summary İndirim kodunu silmeye yarar
     * @param {number} [discountId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteDiscount(discountId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary İndirim kodlarının listesini getirir
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Discount listesinde arama yapılacak kelimeyi barındırır
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listDiscounts(page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PromotionAdministrationQueriesListDiscountsQueryResult>>;
};
/**
 * PromotionAdministrationApi - factory interface
 * @export
 */
export declare const PromotionAdministrationApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary İndirimin aktiflik durumunu değiştirmeyi sağlar
     * @param {number} [discountId]
     * @param {boolean} [newState]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeDiscountActiveState(discountId?: number, newState?: boolean, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Yeni indirim kodu oluşturmayı sağlar
     * @param {string} [discountCode]
     * @param {number} [discountPercentage]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createDiscount(discountCode?: string, discountPercentage?: number, options?: any): AxiosPromise<PromotionAdministrationCommandsCreateDiscountCommandResult>;
    /**
     *
     * @summary İndirim kodunu silmeye yarar
     * @param {number} [discountId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteDiscount(discountId?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary İndirim kodlarının listesini getirir
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Discount listesinde arama yapılacak kelimeyi barındırır
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listDiscounts(page?: number, itemPerPage?: number, searchKeyword?: string, options?: any): AxiosPromise<PromotionAdministrationQueriesListDiscountsQueryResult>;
};
/**
 * PromotionAdministrationApi - interface
 * @export
 * @interface PromotionAdministrationApi
 */
export interface PromotionAdministrationApiInterface {
    /**
     *
     * @summary İndirimin aktiflik durumunu değiştirmeyi sağlar
     * @param {number} [discountId]
     * @param {boolean} [newState]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromotionAdministrationApiInterface
     */
    changeDiscountActiveState(discountId?: number, newState?: boolean, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Yeni indirim kodu oluşturmayı sağlar
     * @param {string} [discountCode]
     * @param {number} [discountPercentage]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromotionAdministrationApiInterface
     */
    createDiscount(discountCode?: string, discountPercentage?: number, options?: AxiosRequestConfig): AxiosPromise<PromotionAdministrationCommandsCreateDiscountCommandResult>;
    /**
     *
     * @summary İndirim kodunu silmeye yarar
     * @param {number} [discountId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromotionAdministrationApiInterface
     */
    deleteDiscount(discountId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary İndirim kodlarının listesini getirir
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Discount listesinde arama yapılacak kelimeyi barındırır
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromotionAdministrationApiInterface
     */
    listDiscounts(page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig): AxiosPromise<PromotionAdministrationQueriesListDiscountsQueryResult>;
}
/**
 * PromotionAdministrationApi - object-oriented interface
 * @export
 * @class PromotionAdministrationApi
 * @extends {BaseAPI}
 */
export declare class PromotionAdministrationApi extends BaseAPI implements PromotionAdministrationApiInterface {
    /**
     *
     * @summary İndirimin aktiflik durumunu değiştirmeyi sağlar
     * @param {number} [discountId]
     * @param {boolean} [newState]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromotionAdministrationApi
     */
    changeDiscountActiveState(discountId?: number, newState?: boolean, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Yeni indirim kodu oluşturmayı sağlar
     * @param {string} [discountCode]
     * @param {number} [discountPercentage]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromotionAdministrationApi
     */
    createDiscount(discountCode?: string, discountPercentage?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<PromotionAdministrationCommandsCreateDiscountCommandResult, any>>;
    /**
     *
     * @summary İndirim kodunu silmeye yarar
     * @param {number} [discountId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromotionAdministrationApi
     */
    deleteDiscount(discountId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary İndirim kodlarının listesini getirir
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Discount listesinde arama yapılacak kelimeyi barındırır
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromotionAdministrationApi
     */
    listDiscounts(page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<PromotionAdministrationQueriesListDiscountsQueryResult, any>>;
}
