/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { RequestArgs, BaseAPI } from '../base';
import { SubscriptionAdministrationCommandsAddPackageDurationOptionCommandResult } from '../models';
import { SubscriptionAdministrationQueriesListSubscriptionDropdownOptionsQueryResult } from '../models';
import { SubscriptionAdministrationQueriesListSubscriptionOptionsQueryResult } from '../models';
/**
 * SubscriptionAdministrationApi - axios parameter creator
 * @export
 */
export declare const SubscriptionAdministrationApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Haftada kaç günlük eğitim alınabileceğine dair paket seçeneklerine ekleme yapar.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addDayOptionToSubscriptionPackages: (day?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Paket içerisinde günde kaç dakika eğitim alabileceği seçeneğini ekler.
     * @param {number} [minutes]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addMinutesPerDayOptionToSubscriptionPackages: (minutes?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Paket süresi seçeneği ekler.
     * @param {string} [durationName]
     * @param {number} [durationAsMonth]
     * @param {number} [discountRate]
     * @param {string} [description]
     * @param {number} [dayOptionId]
     * @param {number} [minuteOptionId]
     * @param {number} [pricePerMint]
     * @param {number} [discountedAmount]
     * @param {number} [total]
     * @param {number} [totalDiscounted]
     * @param {number} [totalMinutes]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addPackageDurationOptionToSubscriptionPackages: (durationName?: string, durationAsMonth?: number, discountRate?: number, description?: string, dayOptionId?: number, minuteOptionId?: number, pricePerMint?: number, discountedAmount?: number, total?: number, totalDiscounted?: number, totalMinutes?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Dakika başına ücreti günceller.
     * @param {number} [price]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changePricePerMinuteForSubscriptionPackages: (price?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSubscriptionDropdownOptions: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Abonelik seçeneklerini getirir.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSubscriptionOptionsForManagement: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Haftada kaç günlük eğitim alınabileceğine dair paket seçeneklerinden bir öğeyi siler.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeDayOptionFromSubscriptionPackages: (day?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Paket içerisinde günde kaç dakika eğitim alabileceği seçeneğini siler.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeMinutesPerDayOptionFromSubscriptionPackages: (day?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Paket süresi seçeneğini siler.
     * @param {number} [packageDurationId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removePackageDurationOptionFromSubscriptionPackages: (packageDurationId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * SubscriptionAdministrationApi - functional programming interface
 * @export
 */
export declare const SubscriptionAdministrationApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Haftada kaç günlük eğitim alınabileceğine dair paket seçeneklerine ekleme yapar.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addDayOptionToSubscriptionPackages(day?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Paket içerisinde günde kaç dakika eğitim alabileceği seçeneğini ekler.
     * @param {number} [minutes]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addMinutesPerDayOptionToSubscriptionPackages(minutes?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Paket süresi seçeneği ekler.
     * @param {string} [durationName]
     * @param {number} [durationAsMonth]
     * @param {number} [discountRate]
     * @param {string} [description]
     * @param {number} [dayOptionId]
     * @param {number} [minuteOptionId]
     * @param {number} [pricePerMint]
     * @param {number} [discountedAmount]
     * @param {number} [total]
     * @param {number} [totalDiscounted]
     * @param {number} [totalMinutes]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addPackageDurationOptionToSubscriptionPackages(durationName?: string, durationAsMonth?: number, discountRate?: number, description?: string, dayOptionId?: number, minuteOptionId?: number, pricePerMint?: number, discountedAmount?: number, total?: number, totalDiscounted?: number, totalMinutes?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionAdministrationCommandsAddPackageDurationOptionCommandResult>>;
    /**
     *
     * @summary Dakika başına ücreti günceller.
     * @param {number} [price]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changePricePerMinuteForSubscriptionPackages(price?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSubscriptionDropdownOptions(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionAdministrationQueriesListSubscriptionDropdownOptionsQueryResult>>;
    /**
     *
     * @summary Abonelik seçeneklerini getirir.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSubscriptionOptionsForManagement(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionAdministrationQueriesListSubscriptionOptionsQueryResult>>;
    /**
     *
     * @summary Haftada kaç günlük eğitim alınabileceğine dair paket seçeneklerinden bir öğeyi siler.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeDayOptionFromSubscriptionPackages(day?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Paket içerisinde günde kaç dakika eğitim alabileceği seçeneğini siler.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeMinutesPerDayOptionFromSubscriptionPackages(day?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Paket süresi seçeneğini siler.
     * @param {number} [packageDurationId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removePackageDurationOptionFromSubscriptionPackages(packageDurationId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
};
/**
 * SubscriptionAdministrationApi - factory interface
 * @export
 */
export declare const SubscriptionAdministrationApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Haftada kaç günlük eğitim alınabileceğine dair paket seçeneklerine ekleme yapar.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addDayOptionToSubscriptionPackages(day?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Paket içerisinde günde kaç dakika eğitim alabileceği seçeneğini ekler.
     * @param {number} [minutes]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addMinutesPerDayOptionToSubscriptionPackages(minutes?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Paket süresi seçeneği ekler.
     * @param {string} [durationName]
     * @param {number} [durationAsMonth]
     * @param {number} [discountRate]
     * @param {string} [description]
     * @param {number} [dayOptionId]
     * @param {number} [minuteOptionId]
     * @param {number} [pricePerMint]
     * @param {number} [discountedAmount]
     * @param {number} [total]
     * @param {number} [totalDiscounted]
     * @param {number} [totalMinutes]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addPackageDurationOptionToSubscriptionPackages(durationName?: string, durationAsMonth?: number, discountRate?: number, description?: string, dayOptionId?: number, minuteOptionId?: number, pricePerMint?: number, discountedAmount?: number, total?: number, totalDiscounted?: number, totalMinutes?: number, options?: any): AxiosPromise<SubscriptionAdministrationCommandsAddPackageDurationOptionCommandResult>;
    /**
     *
     * @summary Dakika başına ücreti günceller.
     * @param {number} [price]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changePricePerMinuteForSubscriptionPackages(price?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSubscriptionDropdownOptions(options?: any): AxiosPromise<SubscriptionAdministrationQueriesListSubscriptionDropdownOptionsQueryResult>;
    /**
     *
     * @summary Abonelik seçeneklerini getirir.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSubscriptionOptionsForManagement(options?: any): AxiosPromise<SubscriptionAdministrationQueriesListSubscriptionOptionsQueryResult>;
    /**
     *
     * @summary Haftada kaç günlük eğitim alınabileceğine dair paket seçeneklerinden bir öğeyi siler.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeDayOptionFromSubscriptionPackages(day?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Paket içerisinde günde kaç dakika eğitim alabileceği seçeneğini siler.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeMinutesPerDayOptionFromSubscriptionPackages(day?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Paket süresi seçeneğini siler.
     * @param {number} [packageDurationId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removePackageDurationOptionFromSubscriptionPackages(packageDurationId?: number, options?: any): AxiosPromise<object>;
};
/**
 * SubscriptionAdministrationApi - interface
 * @export
 * @interface SubscriptionAdministrationApi
 */
export interface SubscriptionAdministrationApiInterface {
    /**
     *
     * @summary Haftada kaç günlük eğitim alınabileceğine dair paket seçeneklerine ekleme yapar.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApiInterface
     */
    addDayOptionToSubscriptionPackages(day?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Paket içerisinde günde kaç dakika eğitim alabileceği seçeneğini ekler.
     * @param {number} [minutes]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApiInterface
     */
    addMinutesPerDayOptionToSubscriptionPackages(minutes?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Paket süresi seçeneği ekler.
     * @param {string} [durationName]
     * @param {number} [durationAsMonth]
     * @param {number} [discountRate]
     * @param {string} [description]
     * @param {number} [dayOptionId]
     * @param {number} [minuteOptionId]
     * @param {number} [pricePerMint]
     * @param {number} [discountedAmount]
     * @param {number} [total]
     * @param {number} [totalDiscounted]
     * @param {number} [totalMinutes]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApiInterface
     */
    addPackageDurationOptionToSubscriptionPackages(durationName?: string, durationAsMonth?: number, discountRate?: number, description?: string, dayOptionId?: number, minuteOptionId?: number, pricePerMint?: number, discountedAmount?: number, total?: number, totalDiscounted?: number, totalMinutes?: number, options?: AxiosRequestConfig): AxiosPromise<SubscriptionAdministrationCommandsAddPackageDurationOptionCommandResult>;
    /**
     *
     * @summary Dakika başına ücreti günceller.
     * @param {number} [price]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApiInterface
     */
    changePricePerMinuteForSubscriptionPackages(price?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApiInterface
     */
    listSubscriptionDropdownOptions(options?: AxiosRequestConfig): AxiosPromise<SubscriptionAdministrationQueriesListSubscriptionDropdownOptionsQueryResult>;
    /**
     *
     * @summary Abonelik seçeneklerini getirir.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApiInterface
     */
    listSubscriptionOptionsForManagement(options?: AxiosRequestConfig): AxiosPromise<SubscriptionAdministrationQueriesListSubscriptionOptionsQueryResult>;
    /**
     *
     * @summary Haftada kaç günlük eğitim alınabileceğine dair paket seçeneklerinden bir öğeyi siler.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApiInterface
     */
    removeDayOptionFromSubscriptionPackages(day?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Paket içerisinde günde kaç dakika eğitim alabileceği seçeneğini siler.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApiInterface
     */
    removeMinutesPerDayOptionFromSubscriptionPackages(day?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Paket süresi seçeneğini siler.
     * @param {number} [packageDurationId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApiInterface
     */
    removePackageDurationOptionFromSubscriptionPackages(packageDurationId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
}
/**
 * SubscriptionAdministrationApi - object-oriented interface
 * @export
 * @class SubscriptionAdministrationApi
 * @extends {BaseAPI}
 */
export declare class SubscriptionAdministrationApi extends BaseAPI implements SubscriptionAdministrationApiInterface {
    /**
     *
     * @summary Haftada kaç günlük eğitim alınabileceğine dair paket seçeneklerine ekleme yapar.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApi
     */
    addDayOptionToSubscriptionPackages(day?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Paket içerisinde günde kaç dakika eğitim alabileceği seçeneğini ekler.
     * @param {number} [minutes]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApi
     */
    addMinutesPerDayOptionToSubscriptionPackages(minutes?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Paket süresi seçeneği ekler.
     * @param {string} [durationName]
     * @param {number} [durationAsMonth]
     * @param {number} [discountRate]
     * @param {string} [description]
     * @param {number} [dayOptionId]
     * @param {number} [minuteOptionId]
     * @param {number} [pricePerMint]
     * @param {number} [discountedAmount]
     * @param {number} [total]
     * @param {number} [totalDiscounted]
     * @param {number} [totalMinutes]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApi
     */
    addPackageDurationOptionToSubscriptionPackages(durationName?: string, durationAsMonth?: number, discountRate?: number, description?: string, dayOptionId?: number, minuteOptionId?: number, pricePerMint?: number, discountedAmount?: number, total?: number, totalDiscounted?: number, totalMinutes?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<SubscriptionAdministrationCommandsAddPackageDurationOptionCommandResult, any>>;
    /**
     *
     * @summary Dakika başına ücreti günceller.
     * @param {number} [price]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApi
     */
    changePricePerMinuteForSubscriptionPackages(price?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApi
     */
    listSubscriptionDropdownOptions(options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<SubscriptionAdministrationQueriesListSubscriptionDropdownOptionsQueryResult, any>>;
    /**
     *
     * @summary Abonelik seçeneklerini getirir.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApi
     */
    listSubscriptionOptionsForManagement(options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<SubscriptionAdministrationQueriesListSubscriptionOptionsQueryResult, any>>;
    /**
     *
     * @summary Haftada kaç günlük eğitim alınabileceğine dair paket seçeneklerinden bir öğeyi siler.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApi
     */
    removeDayOptionFromSubscriptionPackages(day?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Paket içerisinde günde kaç dakika eğitim alabileceği seçeneğini siler.
     * @param {number} [day]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApi
     */
    removeMinutesPerDayOptionFromSubscriptionPackages(day?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Paket süresi seçeneğini siler.
     * @param {number} [packageDurationId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionAdministrationApi
     */
    removePackageDurationOptionFromSubscriptionPackages(packageDurationId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
}
