/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { RequestArgs, BaseAPI } from '../base';
import { WordTutorialQueriesListMyFavoritesQueryResult } from '../models';
/**
 * WordTutorialApi - axios parameter creator
 * @export
 */
export declare const WordTutorialApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Kullanıcının kelime eğitimini favori olarak işaretlemesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteWordTutorial: (wordTutorialId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini beğenmesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    likeWordTutorial: (wordTutorialId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kişinin favori olarak kaydettiği kelimeleri listeler
     * @param {number} [lastId]
     * @param {string} [query]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listMyFavoriteWordTutorials: (lastId?: number, query?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini favorilerinden çıkartmasını sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unfavoriteWordTutorial: (wordTutorialId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini beğenmesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unlikeWordTutorial: (wordTutorialId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kullanıcı tarafından gerçekleştirilen kelime eğitimi paylaşımını sunucuya bildirir.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    wordTutorialShared: (wordTutorialId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kullanıcının izlediği videoyu sunucuya bildirir.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    wordTutorialVideoWatched: (wordTutorialId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * WordTutorialApi - functional programming interface
 * @export
 */
export declare const WordTutorialApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Kullanıcının kelime eğitimini favori olarak işaretlemesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini beğenmesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    likeWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Kişinin favori olarak kaydettiği kelimeleri listeler
     * @param {number} [lastId]
     * @param {string} [query]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listMyFavoriteWordTutorials(lastId?: number, query?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WordTutorialQueriesListMyFavoritesQueryResult>>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini favorilerinden çıkartmasını sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unfavoriteWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini beğenmesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unlikeWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Kullanıcı tarafından gerçekleştirilen kelime eğitimi paylaşımını sunucuya bildirir.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    wordTutorialShared(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Kullanıcının izlediği videoyu sunucuya bildirir.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    wordTutorialVideoWatched(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
};
/**
 * WordTutorialApi - factory interface
 * @export
 */
export declare const WordTutorialApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Kullanıcının kelime eğitimini favori olarak işaretlemesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteWordTutorial(wordTutorialId?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini beğenmesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    likeWordTutorial(wordTutorialId?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Kişinin favori olarak kaydettiği kelimeleri listeler
     * @param {number} [lastId]
     * @param {string} [query]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listMyFavoriteWordTutorials(lastId?: number, query?: string, options?: any): AxiosPromise<WordTutorialQueriesListMyFavoritesQueryResult>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini favorilerinden çıkartmasını sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unfavoriteWordTutorial(wordTutorialId?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini beğenmesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unlikeWordTutorial(wordTutorialId?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Kullanıcı tarafından gerçekleştirilen kelime eğitimi paylaşımını sunucuya bildirir.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    wordTutorialShared(wordTutorialId?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Kullanıcının izlediği videoyu sunucuya bildirir.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    wordTutorialVideoWatched(wordTutorialId?: number, options?: any): AxiosPromise<object>;
};
/**
 * WordTutorialApi - interface
 * @export
 * @interface WordTutorialApi
 */
export interface WordTutorialApiInterface {
    /**
     *
     * @summary Kullanıcının kelime eğitimini favori olarak işaretlemesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApiInterface
     */
    favoriteWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini beğenmesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApiInterface
     */
    likeWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Kişinin favori olarak kaydettiği kelimeleri listeler
     * @param {number} [lastId]
     * @param {string} [query]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApiInterface
     */
    listMyFavoriteWordTutorials(lastId?: number, query?: string, options?: AxiosRequestConfig): AxiosPromise<WordTutorialQueriesListMyFavoritesQueryResult>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini favorilerinden çıkartmasını sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApiInterface
     */
    unfavoriteWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini beğenmesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApiInterface
     */
    unlikeWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Kullanıcı tarafından gerçekleştirilen kelime eğitimi paylaşımını sunucuya bildirir.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApiInterface
     */
    wordTutorialShared(wordTutorialId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Kullanıcının izlediği videoyu sunucuya bildirir.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApiInterface
     */
    wordTutorialVideoWatched(wordTutorialId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
}
/**
 * WordTutorialApi - object-oriented interface
 * @export
 * @class WordTutorialApi
 * @extends {BaseAPI}
 */
export declare class WordTutorialApi extends BaseAPI implements WordTutorialApiInterface {
    /**
     *
     * @summary Kullanıcının kelime eğitimini favori olarak işaretlemesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApi
     */
    favoriteWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini beğenmesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApi
     */
    likeWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Kişinin favori olarak kaydettiği kelimeleri listeler
     * @param {number} [lastId]
     * @param {string} [query]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApi
     */
    listMyFavoriteWordTutorials(lastId?: number, query?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<WordTutorialQueriesListMyFavoritesQueryResult, any>>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini favorilerinden çıkartmasını sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApi
     */
    unfavoriteWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Kullanıcının kelime eğitimini beğenmesini sağlar.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApi
     */
    unlikeWordTutorial(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Kullanıcı tarafından gerçekleştirilen kelime eğitimi paylaşımını sunucuya bildirir.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApi
     */
    wordTutorialShared(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Kullanıcının izlediği videoyu sunucuya bildirir.
     * @param {number} [wordTutorialId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialApi
     */
    wordTutorialVideoWatched(wordTutorialId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
}
