/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, setSearchParams, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, BaseAPI } from '../base';
/**
 * IyzicoApi - axios parameter creator
 * @export
 */
export const IyzicoApiAxiosParamCreator = function (configuration) {
    return {
        /**
         *
         * @summary Iyzico subscribe result\'unda geri dönülen endpointtir
         * @param {string} [token]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iyzicoRedirectResult: (token, options = {}) => __awaiter(this, void 0, void 0, function* () {
            const localVarPath = `/api/Iyzico/IyzicoRedirectResult`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'POST' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();
            if (token !== undefined) {
                localVarFormParams.append('token', token);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            localVarRequestOptions.data = localVarFormParams;
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
        /**
         *
         * @summary Iyzico subscribe webhook\'unun dürttüğü adrestir
         * @param {number} [iyziEventTime]
         * @param {string} [iyziEventType]
         * @param {string} [iyziReferenceCode]
         * @param {string} [token]
         * @param {string} [paymentId]
         * @param {string} [paymentConversationId]
         * @param {string} [status]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iyzicoWebhookResult: (iyziEventTime, iyziEventType, iyziReferenceCode, token, paymentId, paymentConversationId, status, options = {}) => __awaiter(this, void 0, void 0, function* () {
            const localVarPath = `/api/Iyzico/IyzicoWebhookResult`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'POST' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();
            if (iyziEventTime !== undefined) {
                localVarFormParams.append('IyziEventTime', iyziEventTime);
            }
            if (iyziEventType !== undefined) {
                localVarFormParams.append('IyziEventType', iyziEventType);
            }
            if (iyziReferenceCode !== undefined) {
                localVarFormParams.append('IyziReferenceCode', iyziReferenceCode);
            }
            if (token !== undefined) {
                localVarFormParams.append('Token', token);
            }
            if (paymentId !== undefined) {
                localVarFormParams.append('PaymentId', paymentId);
            }
            if (paymentConversationId !== undefined) {
                localVarFormParams.append('PaymentConversationId', paymentConversationId);
            }
            if (status !== undefined) {
                localVarFormParams.append('Status', status);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            localVarRequestOptions.data = localVarFormParams;
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
    };
};
/**
 * IyzicoApi - functional programming interface
 * @export
 */
export const IyzicoApiFp = function (configuration) {
    const localVarAxiosParamCreator = IyzicoApiAxiosParamCreator(configuration);
    return {
        /**
         *
         * @summary Iyzico subscribe result\'unda geri dönülen endpointtir
         * @param {string} [token]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iyzicoRedirectResult(token, options) {
            return __awaiter(this, void 0, void 0, function* () {
                const localVarAxiosArgs = yield localVarAxiosParamCreator.iyzicoRedirectResult(token, options);
                return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
            });
        },
        /**
         *
         * @summary Iyzico subscribe webhook\'unun dürttüğü adrestir
         * @param {number} [iyziEventTime]
         * @param {string} [iyziEventType]
         * @param {string} [iyziReferenceCode]
         * @param {string} [token]
         * @param {string} [paymentId]
         * @param {string} [paymentConversationId]
         * @param {string} [status]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iyzicoWebhookResult(iyziEventTime, iyziEventType, iyziReferenceCode, token, paymentId, paymentConversationId, status, options) {
            return __awaiter(this, void 0, void 0, function* () {
                const localVarAxiosArgs = yield localVarAxiosParamCreator.iyzicoWebhookResult(iyziEventTime, iyziEventType, iyziReferenceCode, token, paymentId, paymentConversationId, status, options);
                return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
            });
        },
    };
};
/**
 * IyzicoApi - factory interface
 * @export
 */
export const IyzicoApiFactory = function (configuration, basePath, axios) {
    const localVarFp = IyzicoApiFp(configuration);
    return {
        /**
         *
         * @summary Iyzico subscribe result\'unda geri dönülen endpointtir
         * @param {string} [token]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iyzicoRedirectResult(token, options) {
            return localVarFp.iyzicoRedirectResult(token, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Iyzico subscribe webhook\'unun dürttüğü adrestir
         * @param {number} [iyziEventTime]
         * @param {string} [iyziEventType]
         * @param {string} [iyziReferenceCode]
         * @param {string} [token]
         * @param {string} [paymentId]
         * @param {string} [paymentConversationId]
         * @param {string} [status]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iyzicoWebhookResult(iyziEventTime, iyziEventType, iyziReferenceCode, token, paymentId, paymentConversationId, status, options) {
            return localVarFp.iyzicoWebhookResult(iyziEventTime, iyziEventType, iyziReferenceCode, token, paymentId, paymentConversationId, status, options).then((request) => request(axios, basePath));
        },
    };
};
/**
 * IyzicoApi - object-oriented interface
 * @export
 * @class IyzicoApi
 * @extends {BaseAPI}
 */
export class IyzicoApi extends BaseAPI {
    /**
     *
     * @summary Iyzico subscribe result\'unda geri dönülen endpointtir
     * @param {string} [token]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoApi
     */
    iyzicoRedirectResult(token, options) {
        return IyzicoApiFp(this.configuration).iyzicoRedirectResult(token, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Iyzico subscribe webhook\'unun dürttüğü adrestir
     * @param {number} [iyziEventTime]
     * @param {string} [iyziEventType]
     * @param {string} [iyziReferenceCode]
     * @param {string} [token]
     * @param {string} [paymentId]
     * @param {string} [paymentConversationId]
     * @param {string} [status]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoApi
     */
    iyzicoWebhookResult(iyziEventTime, iyziEventType, iyziReferenceCode, token, paymentId, paymentConversationId, status, options) {
        return IyzicoApiFp(this.configuration).iyzicoWebhookResult(iyziEventTime, iyziEventType, iyziReferenceCode, token, paymentId, paymentConversationId, status, options).then((request) => request(this.axios, this.basePath));
    }
}
