/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { RequestArgs, BaseAPI } from '../base';
/**
 * IyzicoApi - axios parameter creator
 * @export
 */
export declare const IyzicoApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Iyzico subscribe result\'unda geri dönülen endpointtir
     * @param {string} [token]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    iyzicoRedirectResult: (token?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Iyzico subscribe webhook\'unun dürttüğü adrestir
     * @param {number} [iyziEventTime]
     * @param {string} [iyziEventType]
     * @param {string} [iyziReferenceCode]
     * @param {string} [token]
     * @param {string} [paymentId]
     * @param {string} [paymentConversationId]
     * @param {string} [status]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    iyzicoWebhookResult: (iyziEventTime?: number, iyziEventType?: string, iyziReferenceCode?: string, token?: string, paymentId?: string, paymentConversationId?: string, status?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * IyzicoApi - functional programming interface
 * @export
 */
export declare const IyzicoApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Iyzico subscribe result\'unda geri dönülen endpointtir
     * @param {string} [token]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    iyzicoRedirectResult(token?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Iyzico subscribe webhook\'unun dürttüğü adrestir
     * @param {number} [iyziEventTime]
     * @param {string} [iyziEventType]
     * @param {string} [iyziReferenceCode]
     * @param {string} [token]
     * @param {string} [paymentId]
     * @param {string} [paymentConversationId]
     * @param {string} [status]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    iyzicoWebhookResult(iyziEventTime?: number, iyziEventType?: string, iyziReferenceCode?: string, token?: string, paymentId?: string, paymentConversationId?: string, status?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>>;
};
/**
 * IyzicoApi - factory interface
 * @export
 */
export declare const IyzicoApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Iyzico subscribe result\'unda geri dönülen endpointtir
     * @param {string} [token]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    iyzicoRedirectResult(token?: string, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary Iyzico subscribe webhook\'unun dürttüğü adrestir
     * @param {number} [iyziEventTime]
     * @param {string} [iyziEventType]
     * @param {string} [iyziReferenceCode]
     * @param {string} [token]
     * @param {string} [paymentId]
     * @param {string} [paymentConversationId]
     * @param {string} [status]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    iyzicoWebhookResult(iyziEventTime?: number, iyziEventType?: string, iyziReferenceCode?: string, token?: string, paymentId?: string, paymentConversationId?: string, status?: string, options?: any): AxiosPromise<string>;
};
/**
 * IyzicoApi - interface
 * @export
 * @interface IyzicoApi
 */
export interface IyzicoApiInterface {
    /**
     *
     * @summary Iyzico subscribe result\'unda geri dönülen endpointtir
     * @param {string} [token]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoApiInterface
     */
    iyzicoRedirectResult(token?: string, options?: AxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Iyzico subscribe webhook\'unun dürttüğü adrestir
     * @param {number} [iyziEventTime]
     * @param {string} [iyziEventType]
     * @param {string} [iyziReferenceCode]
     * @param {string} [token]
     * @param {string} [paymentId]
     * @param {string} [paymentConversationId]
     * @param {string} [status]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoApiInterface
     */
    iyzicoWebhookResult(iyziEventTime?: number, iyziEventType?: string, iyziReferenceCode?: string, token?: string, paymentId?: string, paymentConversationId?: string, status?: string, options?: AxiosRequestConfig): AxiosPromise<string>;
}
/**
 * IyzicoApi - object-oriented interface
 * @export
 * @class IyzicoApi
 * @extends {BaseAPI}
 */
export declare class IyzicoApi extends BaseAPI implements IyzicoApiInterface {
    /**
     *
     * @summary Iyzico subscribe result\'unda geri dönülen endpointtir
     * @param {string} [token]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoApi
     */
    iyzicoRedirectResult(token?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any>>;
    /**
     *
     * @summary Iyzico subscribe webhook\'unun dürttüğü adrestir
     * @param {number} [iyziEventTime]
     * @param {string} [iyziEventType]
     * @param {string} [iyziReferenceCode]
     * @param {string} [token]
     * @param {string} [paymentId]
     * @param {string} [paymentConversationId]
     * @param {string} [status]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoApi
     */
    iyzicoWebhookResult(iyziEventTime?: number, iyziEventType?: string, iyziReferenceCode?: string, token?: string, paymentId?: string, paymentConversationId?: string, status?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<string, any>>;
}
