/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { RequestArgs, BaseAPI } from '../base';
import { IyzicoSubscriptionCommandsCreateCommand } from '../models';
import { IyzicoSubscriptionCommandsCreateCommandResult } from '../models';
import { IyzicoSubscriptionCommandsUpdateCommand } from '../models';
import { IyzicoSubscriptionQueriesCommonSubscriptionDropdown } from '../models';
import { IyzicoSubscriptionQueriesIyzicoSubscriptionDetails } from '../models';
import { IyzicoSubscriptionQueriesListQueryResult } from '../models';
/**
 * IyzicoSubscriptionApi - axios parameter creator
 * @export
 */
export declare const IyzicoSubscriptionApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {IyzicoSubscriptionCommandsCreateCommand} [iyzicoSubscriptionCommandsCreateCommand]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSubscription: (iyzicoSubscriptionCommandsCreateCommand?: IyzicoSubscriptionCommandsCreateCommand, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteByIdSubscriptionPlan: (id?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDetailsByIdSubscriptionPlan: (id?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDropDownPackageDurationOptions: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDropDownSubscriptionDayOptions: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDropDownSubscriptionMinutesPerDayOptions: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Film kategorisinde arama yapılacak kelime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSubscriptionPlan: (page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {IyzicoSubscriptionCommandsUpdateCommand} [iyzicoSubscriptionCommandsUpdateCommand]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSubscription: (iyzicoSubscriptionCommandsUpdateCommand?: IyzicoSubscriptionCommandsUpdateCommand, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * IyzicoSubscriptionApi - functional programming interface
 * @export
 */
export declare const IyzicoSubscriptionApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {IyzicoSubscriptionCommandsCreateCommand} [iyzicoSubscriptionCommandsCreateCommand]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSubscription(iyzicoSubscriptionCommandsCreateCommand?: IyzicoSubscriptionCommandsCreateCommand, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IyzicoSubscriptionCommandsCreateCommandResult>>;
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteByIdSubscriptionPlan(id?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>>;
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDetailsByIdSubscriptionPlan(id?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IyzicoSubscriptionQueriesIyzicoSubscriptionDetails>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDropDownPackageDurationOptions(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IyzicoSubscriptionQueriesCommonSubscriptionDropdown>>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDropDownSubscriptionDayOptions(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IyzicoSubscriptionQueriesCommonSubscriptionDropdown>>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDropDownSubscriptionMinutesPerDayOptions(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IyzicoSubscriptionQueriesCommonSubscriptionDropdown>>>;
    /**
     *
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Film kategorisinde arama yapılacak kelime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSubscriptionPlan(page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IyzicoSubscriptionQueriesListQueryResult>>;
    /**
     *
     * @param {IyzicoSubscriptionCommandsUpdateCommand} [iyzicoSubscriptionCommandsUpdateCommand]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSubscription(iyzicoSubscriptionCommandsUpdateCommand?: IyzicoSubscriptionCommandsUpdateCommand, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IyzicoSubscriptionCommandsCreateCommandResult>>;
};
/**
 * IyzicoSubscriptionApi - factory interface
 * @export
 */
export declare const IyzicoSubscriptionApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {IyzicoSubscriptionCommandsCreateCommand} [iyzicoSubscriptionCommandsCreateCommand]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSubscription(iyzicoSubscriptionCommandsCreateCommand?: IyzicoSubscriptionCommandsCreateCommand, options?: any): AxiosPromise<IyzicoSubscriptionCommandsCreateCommandResult>;
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteByIdSubscriptionPlan(id?: number, options?: any): AxiosPromise<string>;
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDetailsByIdSubscriptionPlan(id?: number, options?: any): AxiosPromise<IyzicoSubscriptionQueriesIyzicoSubscriptionDetails>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDropDownPackageDurationOptions(options?: any): AxiosPromise<Array<IyzicoSubscriptionQueriesCommonSubscriptionDropdown>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDropDownSubscriptionDayOptions(options?: any): AxiosPromise<Array<IyzicoSubscriptionQueriesCommonSubscriptionDropdown>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDropDownSubscriptionMinutesPerDayOptions(options?: any): AxiosPromise<Array<IyzicoSubscriptionQueriesCommonSubscriptionDropdown>>;
    /**
     *
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Film kategorisinde arama yapılacak kelime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSubscriptionPlan(page?: number, itemPerPage?: number, searchKeyword?: string, options?: any): AxiosPromise<IyzicoSubscriptionQueriesListQueryResult>;
    /**
     *
     * @param {IyzicoSubscriptionCommandsUpdateCommand} [iyzicoSubscriptionCommandsUpdateCommand]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateSubscription(iyzicoSubscriptionCommandsUpdateCommand?: IyzicoSubscriptionCommandsUpdateCommand, options?: any): AxiosPromise<IyzicoSubscriptionCommandsCreateCommandResult>;
};
/**
 * IyzicoSubscriptionApi - interface
 * @export
 * @interface IyzicoSubscriptionApi
 */
export interface IyzicoSubscriptionApiInterface {
    /**
     *
     * @param {IyzicoSubscriptionCommandsCreateCommand} [iyzicoSubscriptionCommandsCreateCommand]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApiInterface
     */
    createSubscription(iyzicoSubscriptionCommandsCreateCommand?: IyzicoSubscriptionCommandsCreateCommand, options?: AxiosRequestConfig): AxiosPromise<IyzicoSubscriptionCommandsCreateCommandResult>;
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApiInterface
     */
    deleteByIdSubscriptionPlan(id?: number, options?: AxiosRequestConfig): AxiosPromise<string>;
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApiInterface
     */
    getDetailsByIdSubscriptionPlan(id?: number, options?: AxiosRequestConfig): AxiosPromise<IyzicoSubscriptionQueriesIyzicoSubscriptionDetails>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApiInterface
     */
    getDropDownPackageDurationOptions(options?: AxiosRequestConfig): AxiosPromise<Array<IyzicoSubscriptionQueriesCommonSubscriptionDropdown>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApiInterface
     */
    getDropDownSubscriptionDayOptions(options?: AxiosRequestConfig): AxiosPromise<Array<IyzicoSubscriptionQueriesCommonSubscriptionDropdown>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApiInterface
     */
    getDropDownSubscriptionMinutesPerDayOptions(options?: AxiosRequestConfig): AxiosPromise<Array<IyzicoSubscriptionQueriesCommonSubscriptionDropdown>>;
    /**
     *
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Film kategorisinde arama yapılacak kelime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApiInterface
     */
    listSubscriptionPlan(page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig): AxiosPromise<IyzicoSubscriptionQueriesListQueryResult>;
    /**
     *
     * @param {IyzicoSubscriptionCommandsUpdateCommand} [iyzicoSubscriptionCommandsUpdateCommand]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApiInterface
     */
    updateSubscription(iyzicoSubscriptionCommandsUpdateCommand?: IyzicoSubscriptionCommandsUpdateCommand, options?: AxiosRequestConfig): AxiosPromise<IyzicoSubscriptionCommandsCreateCommandResult>;
}
/**
 * IyzicoSubscriptionApi - object-oriented interface
 * @export
 * @class IyzicoSubscriptionApi
 * @extends {BaseAPI}
 */
export declare class IyzicoSubscriptionApi extends BaseAPI implements IyzicoSubscriptionApiInterface {
    /**
     *
     * @param {IyzicoSubscriptionCommandsCreateCommand} [iyzicoSubscriptionCommandsCreateCommand]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApi
     */
    createSubscription(iyzicoSubscriptionCommandsCreateCommand?: IyzicoSubscriptionCommandsCreateCommand, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<IyzicoSubscriptionCommandsCreateCommandResult, any>>;
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApi
     */
    deleteByIdSubscriptionPlan(id?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<string, any>>;
    /**
     *
     * @param {number} [id]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApi
     */
    getDetailsByIdSubscriptionPlan(id?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<IyzicoSubscriptionQueriesIyzicoSubscriptionDetails, any>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApi
     */
    getDropDownPackageDurationOptions(options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<IyzicoSubscriptionQueriesCommonSubscriptionDropdown[], any>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApi
     */
    getDropDownSubscriptionDayOptions(options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<IyzicoSubscriptionQueriesCommonSubscriptionDropdown[], any>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApi
     */
    getDropDownSubscriptionMinutesPerDayOptions(options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<IyzicoSubscriptionQueriesCommonSubscriptionDropdown[], any>>;
    /**
     *
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Film kategorisinde arama yapılacak kelime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApi
     */
    listSubscriptionPlan(page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<IyzicoSubscriptionQueriesListQueryResult, any>>;
    /**
     *
     * @param {IyzicoSubscriptionCommandsUpdateCommand} [iyzicoSubscriptionCommandsUpdateCommand]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IyzicoSubscriptionApi
     */
    updateSubscription(iyzicoSubscriptionCommandsUpdateCommand?: IyzicoSubscriptionCommandsUpdateCommand, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<IyzicoSubscriptionCommandsCreateCommandResult, any>>;
}
