/* tslint:disable */
/* eslint-disable */
/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, BaseAPI } from '../base';
/**
 * PaymentApi - axios parameter creator
 * @export
 */
export const PaymentApiAxiosParamCreator = function (configuration) {
    return {
        /**
         *
         * @summary Kullanıcının şu anki aboneliğini iptal eder. Bu durumda kullanıcı ödeme dönemi sonuna kadar haklarından faydalanabilir veya aboneliğini tekrar aktif hale getirebilir.
         * @param {string} [reason]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelCurrentSubscription: (reason, options = {}) => __awaiter(this, void 0, void 0, function* () {
            const localVarPath = `/api/Payment/CancelCurrentSubscription`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'POST' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearer required
            // http bearer authentication required
            yield setBearerAuthToObject(localVarHeaderParameter, configuration);
            if (reason !== undefined) {
                localVarQueryParameter['Reason'] = reason;
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDropDownSubscriptionOptions: (options = {}) => __awaiter(this, void 0, void 0, function* () {
            const localVarPath = `/api/Payment/ListDropDownSubscriptionOptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'GET' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearer required
            // http bearer authentication required
            yield setBearerAuthToObject(localVarHeaderParameter, configuration);
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
        /**
         *
         * @summary Abonelik seçeneklerini getirir.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSubscriptionOptions: (options = {}) => __awaiter(this, void 0, void 0, function* () {
            const localVarPath = `/api/Payment/ListSubscriptionOptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'GET' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearer required
            // http bearer authentication required
            yield setBearerAuthToObject(localVarHeaderParameter, configuration);
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
        /**
         *
         * @summary Öğrencinin abonelik başlatmasını veya abonelik tipini değiştirmesini sağlar.
         * @param {PaymentCommandsSubscriptionPackageDetails} [paymentCommandsSubscriptionPackageDetails]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscribe: (paymentCommandsSubscriptionPackageDetails, options = {}) => __awaiter(this, void 0, void 0, function* () {
            const localVarPath = `/api/Payment/Subscribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'POST' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearer required
            // http bearer authentication required
            yield setBearerAuthToObject(localVarHeaderParameter, configuration);
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            localVarRequestOptions.data = serializeDataIfNeeded(paymentCommandsSubscriptionPackageDetails, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }),
    };
};
/**
 * PaymentApi - functional programming interface
 * @export
 */
export const PaymentApiFp = function (configuration) {
    const localVarAxiosParamCreator = PaymentApiAxiosParamCreator(configuration);
    return {
        /**
         *
         * @summary Kullanıcının şu anki aboneliğini iptal eder. Bu durumda kullanıcı ödeme dönemi sonuna kadar haklarından faydalanabilir veya aboneliğini tekrar aktif hale getirebilir.
         * @param {string} [reason]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelCurrentSubscription(reason, options) {
            return __awaiter(this, void 0, void 0, function* () {
                const localVarAxiosArgs = yield localVarAxiosParamCreator.cancelCurrentSubscription(reason, options);
                return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
            });
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDropDownSubscriptionOptions(options) {
            return __awaiter(this, void 0, void 0, function* () {
                const localVarAxiosArgs = yield localVarAxiosParamCreator.listDropDownSubscriptionOptions(options);
                return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
            });
        },
        /**
         *
         * @summary Abonelik seçeneklerini getirir.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSubscriptionOptions(options) {
            return __awaiter(this, void 0, void 0, function* () {
                const localVarAxiosArgs = yield localVarAxiosParamCreator.listSubscriptionOptions(options);
                return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
            });
        },
        /**
         *
         * @summary Öğrencinin abonelik başlatmasını veya abonelik tipini değiştirmesini sağlar.
         * @param {PaymentCommandsSubscriptionPackageDetails} [paymentCommandsSubscriptionPackageDetails]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscribe(paymentCommandsSubscriptionPackageDetails, options) {
            return __awaiter(this, void 0, void 0, function* () {
                const localVarAxiosArgs = yield localVarAxiosParamCreator.subscribe(paymentCommandsSubscriptionPackageDetails, options);
                return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
            });
        },
    };
};
/**
 * PaymentApi - factory interface
 * @export
 */
export const PaymentApiFactory = function (configuration, basePath, axios) {
    const localVarFp = PaymentApiFp(configuration);
    return {
        /**
         *
         * @summary Kullanıcının şu anki aboneliğini iptal eder. Bu durumda kullanıcı ödeme dönemi sonuna kadar haklarından faydalanabilir veya aboneliğini tekrar aktif hale getirebilir.
         * @param {string} [reason]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelCurrentSubscription(reason, options) {
            return localVarFp.cancelCurrentSubscription(reason, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDropDownSubscriptionOptions(options) {
            return localVarFp.listDropDownSubscriptionOptions(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Abonelik seçeneklerini getirir.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSubscriptionOptions(options) {
            return localVarFp.listSubscriptionOptions(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Öğrencinin abonelik başlatmasını veya abonelik tipini değiştirmesini sağlar.
         * @param {PaymentCommandsSubscriptionPackageDetails} [paymentCommandsSubscriptionPackageDetails]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscribe(paymentCommandsSubscriptionPackageDetails, options) {
            return localVarFp.subscribe(paymentCommandsSubscriptionPackageDetails, options).then((request) => request(axios, basePath));
        },
    };
};
/**
 * PaymentApi - object-oriented interface
 * @export
 * @class PaymentApi
 * @extends {BaseAPI}
 */
export class PaymentApi extends BaseAPI {
    /**
     *
     * @summary Kullanıcının şu anki aboneliğini iptal eder. Bu durumda kullanıcı ödeme dönemi sonuna kadar haklarından faydalanabilir veya aboneliğini tekrar aktif hale getirebilir.
     * @param {string} [reason]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    cancelCurrentSubscription(reason, options) {
        return PaymentApiFp(this.configuration).cancelCurrentSubscription(reason, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    listDropDownSubscriptionOptions(options) {
        return PaymentApiFp(this.configuration).listDropDownSubscriptionOptions(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Abonelik seçeneklerini getirir.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    listSubscriptionOptions(options) {
        return PaymentApiFp(this.configuration).listSubscriptionOptions(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Öğrencinin abonelik başlatmasını veya abonelik tipini değiştirmesini sağlar.
     * @param {PaymentCommandsSubscriptionPackageDetails} [paymentCommandsSubscriptionPackageDetails]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    subscribe(paymentCommandsSubscriptionPackageDetails, options) {
        return PaymentApiFp(this.configuration).subscribe(paymentCommandsSubscriptionPackageDetails, options).then((request) => request(this.axios, this.basePath));
    }
}
