/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { RequestArgs, BaseAPI } from '../base';
import { WordTutorialCategoryAdministrationCommandsCreateCommandResult } from '../models';
import { WordTutorialCategoryAdministrationQueriesListQueryResult } from '../models';
/**
 * WordTutorialCategoryAdministrationApi - axios parameter creator
 * @export
 */
export declare const WordTutorialCategoryAdministrationApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Kelime eğitimi kategorisinin kapak fotoğrafını değiştirmeyi sağlar
     * @param {File} [newCoverPhoto]
     * @param {number} [wordTutorialCategoryId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeCoverPhotoOfTheWordTutorialCategory: (newCoverPhoto?: File, wordTutorialCategoryId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin açıklamasını değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategoryDescription]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeDescriptionOfTheWordTutorialCategory: (wordTutorialCategoryId?: number, wordTutorialCategoryDescription?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin isim etiketini değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategorySlug]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeSlugOfTheWordTutorialCategory: (wordTutorialCategoryId?: number, wordTutorialCategorySlug?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin ismini değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategoryTitle]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeTitleOfTheWordTutorialCategory: (wordTutorialCategoryId?: number, wordTutorialCategoryTitle?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kelime eğitimi kategorisi eklemeyi sağlar
     * @param {File} [coverPhoto]
     * @param {string} [title]
     * @param {string} [slug]
     * @param {string} [description]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createWordTutorialCategory: (coverPhoto?: File, title?: string, slug?: string, description?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kelime eğitimi kategorisini silmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteWordTutorialCategory: (wordTutorialCategoryId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kelime eğitim kategorilerini listelemeyi sağlar
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Film kategorisinde arama yapılacak kelime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listWordTutorialCategoriesForAdministration: (page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * WordTutorialCategoryAdministrationApi - functional programming interface
 * @export
 */
export declare const WordTutorialCategoryAdministrationApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Kelime eğitimi kategorisinin kapak fotoğrafını değiştirmeyi sağlar
     * @param {File} [newCoverPhoto]
     * @param {number} [wordTutorialCategoryId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeCoverPhotoOfTheWordTutorialCategory(newCoverPhoto?: File, wordTutorialCategoryId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin açıklamasını değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategoryDescription]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeDescriptionOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategoryDescription?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin isim etiketini değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategorySlug]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeSlugOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategorySlug?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin ismini değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategoryTitle]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeTitleOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategoryTitle?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Kelime eğitimi kategorisi eklemeyi sağlar
     * @param {File} [coverPhoto]
     * @param {string} [title]
     * @param {string} [slug]
     * @param {string} [description]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createWordTutorialCategory(coverPhoto?: File, title?: string, slug?: string, description?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WordTutorialCategoryAdministrationCommandsCreateCommandResult>>;
    /**
     *
     * @summary Kelime eğitimi kategorisini silmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteWordTutorialCategory(wordTutorialCategoryId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary Kelime eğitim kategorilerini listelemeyi sağlar
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Film kategorisinde arama yapılacak kelime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listWordTutorialCategoriesForAdministration(page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WordTutorialCategoryAdministrationQueriesListQueryResult>>;
};
/**
 * WordTutorialCategoryAdministrationApi - factory interface
 * @export
 */
export declare const WordTutorialCategoryAdministrationApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Kelime eğitimi kategorisinin kapak fotoğrafını değiştirmeyi sağlar
     * @param {File} [newCoverPhoto]
     * @param {number} [wordTutorialCategoryId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeCoverPhotoOfTheWordTutorialCategory(newCoverPhoto?: File, wordTutorialCategoryId?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin açıklamasını değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategoryDescription]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeDescriptionOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategoryDescription?: string, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin isim etiketini değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategorySlug]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeSlugOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategorySlug?: string, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin ismini değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategoryTitle]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeTitleOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategoryTitle?: string, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Kelime eğitimi kategorisi eklemeyi sağlar
     * @param {File} [coverPhoto]
     * @param {string} [title]
     * @param {string} [slug]
     * @param {string} [description]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createWordTutorialCategory(coverPhoto?: File, title?: string, slug?: string, description?: string, options?: any): AxiosPromise<WordTutorialCategoryAdministrationCommandsCreateCommandResult>;
    /**
     *
     * @summary Kelime eğitimi kategorisini silmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteWordTutorialCategory(wordTutorialCategoryId?: number, options?: any): AxiosPromise<object>;
    /**
     *
     * @summary Kelime eğitim kategorilerini listelemeyi sağlar
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Film kategorisinde arama yapılacak kelime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listWordTutorialCategoriesForAdministration(page?: number, itemPerPage?: number, searchKeyword?: string, options?: any): AxiosPromise<WordTutorialCategoryAdministrationQueriesListQueryResult>;
};
/**
 * WordTutorialCategoryAdministrationApi - interface
 * @export
 * @interface WordTutorialCategoryAdministrationApi
 */
export interface WordTutorialCategoryAdministrationApiInterface {
    /**
     *
     * @summary Kelime eğitimi kategorisinin kapak fotoğrafını değiştirmeyi sağlar
     * @param {File} [newCoverPhoto]
     * @param {number} [wordTutorialCategoryId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApiInterface
     */
    changeCoverPhotoOfTheWordTutorialCategory(newCoverPhoto?: File, wordTutorialCategoryId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin açıklamasını değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategoryDescription]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApiInterface
     */
    changeDescriptionOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategoryDescription?: string, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin isim etiketini değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategorySlug]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApiInterface
     */
    changeSlugOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategorySlug?: string, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin ismini değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategoryTitle]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApiInterface
     */
    changeTitleOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategoryTitle?: string, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Kelime eğitimi kategorisi eklemeyi sağlar
     * @param {File} [coverPhoto]
     * @param {string} [title]
     * @param {string} [slug]
     * @param {string} [description]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApiInterface
     */
    createWordTutorialCategory(coverPhoto?: File, title?: string, slug?: string, description?: string, options?: AxiosRequestConfig): AxiosPromise<WordTutorialCategoryAdministrationCommandsCreateCommandResult>;
    /**
     *
     * @summary Kelime eğitimi kategorisini silmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApiInterface
     */
    deleteWordTutorialCategory(wordTutorialCategoryId?: number, options?: AxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary Kelime eğitim kategorilerini listelemeyi sağlar
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Film kategorisinde arama yapılacak kelime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApiInterface
     */
    listWordTutorialCategoriesForAdministration(page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig): AxiosPromise<WordTutorialCategoryAdministrationQueriesListQueryResult>;
}
/**
 * WordTutorialCategoryAdministrationApi - object-oriented interface
 * @export
 * @class WordTutorialCategoryAdministrationApi
 * @extends {BaseAPI}
 */
export declare class WordTutorialCategoryAdministrationApi extends BaseAPI implements WordTutorialCategoryAdministrationApiInterface {
    /**
     *
     * @summary Kelime eğitimi kategorisinin kapak fotoğrafını değiştirmeyi sağlar
     * @param {File} [newCoverPhoto]
     * @param {number} [wordTutorialCategoryId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApi
     */
    changeCoverPhotoOfTheWordTutorialCategory(newCoverPhoto?: File, wordTutorialCategoryId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin açıklamasını değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategoryDescription]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApi
     */
    changeDescriptionOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategoryDescription?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin isim etiketini değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategorySlug]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApi
     */
    changeSlugOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategorySlug?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Kelime eğitimi kategorisinin ismini değiştirmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {string} [wordTutorialCategoryTitle]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApi
     */
    changeTitleOfTheWordTutorialCategory(wordTutorialCategoryId?: number, wordTutorialCategoryTitle?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Kelime eğitimi kategorisi eklemeyi sağlar
     * @param {File} [coverPhoto]
     * @param {string} [title]
     * @param {string} [slug]
     * @param {string} [description]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApi
     */
    createWordTutorialCategory(coverPhoto?: File, title?: string, slug?: string, description?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<WordTutorialCategoryAdministrationCommandsCreateCommandResult, any>>;
    /**
     *
     * @summary Kelime eğitimi kategorisini silmeyi sağlar
     * @param {number} [wordTutorialCategoryId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApi
     */
    deleteWordTutorialCategory(wordTutorialCategoryId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
    /**
     *
     * @summary Kelime eğitim kategorilerini listelemeyi sağlar
     * @param {number} [page]
     * @param {number} [itemPerPage]
     * @param {string} [searchKeyword] Film kategorisinde arama yapılacak kelime
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryAdministrationApi
     */
    listWordTutorialCategoriesForAdministration(page?: number, itemPerPage?: number, searchKeyword?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<WordTutorialCategoryAdministrationQueriesListQueryResult, any>>;
}
