/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { RequestArgs, BaseAPI } from '../base';
import { WordTutorialCategoryQueriesGetDetailsQueryResult } from '../models';
import { WordTutorialCategoryQueriesListQueryResult } from '../models';
import { WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult } from '../models';
import { WordTutorialCategoryQueriesSearchQueryResult } from '../models';
/**
 * WordTutorialCategoryApi - axios parameter creator
 * @export
 */
export declare const WordTutorialCategoryApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Bir kelime eğitiminin detayını getirir.
     * @param {string} slug
     * @param {string} [selectedWordTutorialSlug]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getWordTutorialCategoryDetails: (slug: string, selectedWordTutorialSlug?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Kelime eğitimi kategori listesini getirir.
     * @param {number} [lastId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listWordTutorialCategories: (lastId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Varolan kelime eğitimi kategorisinin içerisinde gösterilen kelimeleri rastgele olarak yeniler.
     * @param {number} categoryId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refreshWordTutorialsInCategory: (categoryId: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Bulunulan kelime eğitimi kategorisinde kelime araması yapar.
     * @param {string} [wordTutorialCategorySlug] Kelime eğitimi kategorisinin slug\&#39;ıdır.
     * @param {string} [query]
     * @param {number} [lastId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchInWordTutorialCategory: (wordTutorialCategorySlug?: string, query?: string, lastId?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * WordTutorialCategoryApi - functional programming interface
 * @export
 */
export declare const WordTutorialCategoryApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Bir kelime eğitiminin detayını getirir.
     * @param {string} slug
     * @param {string} [selectedWordTutorialSlug]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getWordTutorialCategoryDetails(slug: string, selectedWordTutorialSlug?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WordTutorialCategoryQueriesGetDetailsQueryResult>>;
    /**
     *
     * @summary Kelime eğitimi kategori listesini getirir.
     * @param {number} [lastId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listWordTutorialCategories(lastId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WordTutorialCategoryQueriesListQueryResult>>;
    /**
     *
     * @summary Varolan kelime eğitimi kategorisinin içerisinde gösterilen kelimeleri rastgele olarak yeniler.
     * @param {number} categoryId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refreshWordTutorialsInCategory(categoryId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult>>;
    /**
     *
     * @summary Bulunulan kelime eğitimi kategorisinde kelime araması yapar.
     * @param {string} [wordTutorialCategorySlug] Kelime eğitimi kategorisinin slug\&#39;ıdır.
     * @param {string} [query]
     * @param {number} [lastId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchInWordTutorialCategory(wordTutorialCategorySlug?: string, query?: string, lastId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WordTutorialCategoryQueriesSearchQueryResult>>;
};
/**
 * WordTutorialCategoryApi - factory interface
 * @export
 */
export declare const WordTutorialCategoryApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Bir kelime eğitiminin detayını getirir.
     * @param {string} slug
     * @param {string} [selectedWordTutorialSlug]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getWordTutorialCategoryDetails(slug: string, selectedWordTutorialSlug?: string, options?: any): AxiosPromise<WordTutorialCategoryQueriesGetDetailsQueryResult>;
    /**
     *
     * @summary Kelime eğitimi kategori listesini getirir.
     * @param {number} [lastId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listWordTutorialCategories(lastId?: number, options?: any): AxiosPromise<WordTutorialCategoryQueriesListQueryResult>;
    /**
     *
     * @summary Varolan kelime eğitimi kategorisinin içerisinde gösterilen kelimeleri rastgele olarak yeniler.
     * @param {number} categoryId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refreshWordTutorialsInCategory(categoryId: number, options?: any): AxiosPromise<WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult>;
    /**
     *
     * @summary Bulunulan kelime eğitimi kategorisinde kelime araması yapar.
     * @param {string} [wordTutorialCategorySlug] Kelime eğitimi kategorisinin slug\&#39;ıdır.
     * @param {string} [query]
     * @param {number} [lastId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchInWordTutorialCategory(wordTutorialCategorySlug?: string, query?: string, lastId?: number, options?: any): AxiosPromise<WordTutorialCategoryQueriesSearchQueryResult>;
};
/**
 * WordTutorialCategoryApi - interface
 * @export
 * @interface WordTutorialCategoryApi
 */
export interface WordTutorialCategoryApiInterface {
    /**
     *
     * @summary Bir kelime eğitiminin detayını getirir.
     * @param {string} slug
     * @param {string} [selectedWordTutorialSlug]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryApiInterface
     */
    getWordTutorialCategoryDetails(slug: string, selectedWordTutorialSlug?: string, options?: AxiosRequestConfig): AxiosPromise<WordTutorialCategoryQueriesGetDetailsQueryResult>;
    /**
     *
     * @summary Kelime eğitimi kategori listesini getirir.
     * @param {number} [lastId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryApiInterface
     */
    listWordTutorialCategories(lastId?: number, options?: AxiosRequestConfig): AxiosPromise<WordTutorialCategoryQueriesListQueryResult>;
    /**
     *
     * @summary Varolan kelime eğitimi kategorisinin içerisinde gösterilen kelimeleri rastgele olarak yeniler.
     * @param {number} categoryId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryApiInterface
     */
    refreshWordTutorialsInCategory(categoryId: number, options?: AxiosRequestConfig): AxiosPromise<WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult>;
    /**
     *
     * @summary Bulunulan kelime eğitimi kategorisinde kelime araması yapar.
     * @param {string} [wordTutorialCategorySlug] Kelime eğitimi kategorisinin slug\&#39;ıdır.
     * @param {string} [query]
     * @param {number} [lastId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryApiInterface
     */
    searchInWordTutorialCategory(wordTutorialCategorySlug?: string, query?: string, lastId?: number, options?: AxiosRequestConfig): AxiosPromise<WordTutorialCategoryQueriesSearchQueryResult>;
}
/**
 * WordTutorialCategoryApi - object-oriented interface
 * @export
 * @class WordTutorialCategoryApi
 * @extends {BaseAPI}
 */
export declare class WordTutorialCategoryApi extends BaseAPI implements WordTutorialCategoryApiInterface {
    /**
     *
     * @summary Bir kelime eğitiminin detayını getirir.
     * @param {string} slug
     * @param {string} [selectedWordTutorialSlug]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryApi
     */
    getWordTutorialCategoryDetails(slug: string, selectedWordTutorialSlug?: string, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<WordTutorialCategoryQueriesGetDetailsQueryResult, any>>;
    /**
     *
     * @summary Kelime eğitimi kategori listesini getirir.
     * @param {number} [lastId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryApi
     */
    listWordTutorialCategories(lastId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<WordTutorialCategoryQueriesListQueryResult, any>>;
    /**
     *
     * @summary Varolan kelime eğitimi kategorisinin içerisinde gösterilen kelimeleri rastgele olarak yeniler.
     * @param {number} categoryId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryApi
     */
    refreshWordTutorialsInCategory(categoryId: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<WordTutorialCategoryQueriesRefreshWordTutorialsInCategoryQueryResult, any>>;
    /**
     *
     * @summary Bulunulan kelime eğitimi kategorisinde kelime araması yapar.
     * @param {string} [wordTutorialCategorySlug] Kelime eğitimi kategorisinin slug\&#39;ıdır.
     * @param {string} [query]
     * @param {number} [lastId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WordTutorialCategoryApi
     */
    searchInWordTutorialCategory(wordTutorialCategorySlug?: string, query?: string, lastId?: number, options?: AxiosRequestConfig): Promise<import("axios").AxiosResponse<WordTutorialCategoryQueriesSearchQueryResult, any>>;
}
