/**
 * Advancer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.104
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdvancerModelsAppointmentAppointmentModel } from './advancer-models-appointment-appointment-model';
import { AdvancerModelsAuthenticationAppUserModel } from './advancer-models-authentication-app-user-model';
import { AdvancerModelsJoinTableCreatedAppointmentDueChangeModel } from './advancer-models-join-table-created-appointment-due-change-model';
/**
 *
 * @export
 * @interface AdvancerModelsAppointmentAppointmentChangeModel
 */
export interface AdvancerModelsAppointmentAppointmentChangeModel {
    /**
     *
     * @type {string}
     * @memberof AdvancerModelsAppointmentAppointmentChangeModel
     */
    'createdAt': string;
    /**
     *
     * @type {string}
     * @memberof AdvancerModelsAppointmentAppointmentChangeModel
     */
    'updatedAt': string;
    /**
     *
     * @type {number}
     * @memberof AdvancerModelsAppointmentAppointmentChangeModel
     */
    'id'?: number;
    /**
     *
     * @type {number}
     * @memberof AdvancerModelsAppointmentAppointmentChangeModel
     */
    'changedUserId'?: number;
    /**
     *
     * @type {AdvancerModelsAuthenticationAppUserModel}
     * @memberof AdvancerModelsAppointmentAppointmentChangeModel
     */
    'changedUser'?: AdvancerModelsAuthenticationAppUserModel;
    /**
     *
     * @type {number}
     * @memberof AdvancerModelsAppointmentAppointmentChangeModel
     */
    'changedAppointmentId'?: number;
    /**
     *
     * @type {AdvancerModelsAppointmentAppointmentModel}
     * @memberof AdvancerModelsAppointmentAppointmentChangeModel
     */
    'changedAppointment'?: AdvancerModelsAppointmentAppointmentModel;
    /**
     *
     * @type {Array<AdvancerModelsJoinTableCreatedAppointmentDueChangeModel>}
     * @memberof AdvancerModelsAppointmentAppointmentChangeModel
     */
    'createdAppointmentsDueChange'?: Array<AdvancerModelsJoinTableCreatedAppointmentDueChangeModel> | null;
}
